name:                efb
version:             0.1.0.0
github:              MarleDK/efb
license:             MIT
author:              Jakob Rydhof
maintainer:          jakobrydhof@gmail.com
copyright:           2021 Jakob Rydhof

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/MarleDK/efb#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0
- brick >= 0.58 && < 0.61
- vty 
- text
- typed-process
- directory
- filepath

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  efb-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - efb
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  efb-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - efb
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
